### ISSUE TITLE
Criação de página de perfil para alunos

### ISSUE THREAD

**Issue by PedroFerreiraLopes** [netrometro/gc-at2#10]
#### Descrição
O site deverá, ao mínimo, possuir uma página que mostre o usuário aluno, e suas respectivas contribuições a projetos, com dados do usuário, um elemento img para foto de perfil e uma lista de contribuição do usuário (default: do mais recente ao mais antigo).

#### Screenshots
Estilização a critério do desenvolvedor

#### Arquivos
O arquivo principal deve estar nomeado como _perfilaluno.html_.

#### Tasks
Minimamente, 3 requisitos devem ser cumpridos
- [ ] Um elemento img para adição de foto do aluno
- [ ] Uma lista dos dados do aluno. Com ênfase nos dados: nome, curso e câmpus
- [ ] Uma lista estruturada dos projetos que o aluno contribuiu, ordenados em ordem de data de lançamento.
