### ISSUE TITLE
Pagina de Cadastro

### ISSUE THREAD

**Issue by LeonardoCarneir0** [netrometro/gc-at2#14]
Description
Criar um fomulário de cadastro

Tasks

- [ ] Incluir campo de email, senha, nome e confirmação da senha
- [ ] receber uma confirmação após preencher as informações

**Comment by PedroFerreiraLopes** [comment]
#### Description
Usuário, com perfil de ##ADMIN poderá criar novos usuários. Na página, o admin deve prover o tipo de usuário, seus dados correspondentes e uma senha para acesso, que deverá ser descrita, igualmente, duas vezes. Por fim, o admin irá enviar o formulário de criação e receber um aviso de sucesso ou erro, mostrando respectivamente uma caixa de informação para retorno.
Se houver sucesso, a página também irá apresentar os dados de login e senha para o admin copiar e repassar ao usuário final.

#### Arquivo
Tudo deverá estar implementado do arquivo criacaouser.html

#### Tasks
- [ ] Criar um formulário para cada tipo de perfil (aluno, professor, diretor, etc)
- [ ] Aplicar uma barra de seleção, para escolher um único formulário e apenas apresentá-lo em tela.
- [ ] Criar botão de enviar formulário.
- [ ] Ao pressionar o botão, mostrar uma caixa de informação com o retorno e os dados do usuário, se tiver sucesso.

**Comment by anna-victoria** [comment]
vou pegar essa - Anna Victoria Feliciana
