### ISSUE TITLE
Criar uma tabela de pesquisas criadas

### ISSUE THREAD

**Issue by thiago-abarros** [netrometro/gc-at2#2]
#### Descrição
Uma tabela que mostre as pesquisas realizadas, em progresso e em construção do campus Garanhuns, com um preenchimento mínimo de 3 linhas amostra para os usuários visualizarem.

#### Screenshots
![TabelaPesquisas](https://github.com/netrometro/gc-at2/assets/122405319/ad8a6c4f-5a5b-47ba-ac27-dadbfc1f0ee6)

#### Arquivos
Codifique isso num arquivo chamado PesquisasDisponiveis.html 

#### Tasks
Todas as tasks serão feitas no arquivo PesquisasDisponiveis.html
- [ ] Criar um título que descreva o conteúdo da tabela
- [ ] Criar a tabela com as correspondentes colunas
- [ ] Popular a tabela de acordo com suas labels

**Comment by Guiioff** [comment]
Sugestão de Mudanças nas tarefas:

**Tasks**
Todas as tasks serão feitas no arquivo PesquisasDisponiveis.html

- [ ] Criar o arquivo PesquisasDisponíveis.html
- [ ]  Criar um título que descreva o conteúdo da tabela
- [ ]  Criar a tabela com as correspondentes colunas
- [ ]  Popular a tabela de acordo com suas labels

**Comment by GabrielFerreiraSilva** [comment]
Estou implementando essa feature - Gabriel Ferreira
