### ISSUE TITLE
Menu Suspenso 

### ISSUE THREAD

**Issue by antoniosereno95** [netrometro/gc-at2#3]
##EDIT: Menu Suspenso == Menu Flutuante

#Feature Desenvolver um Menu Suspeso com "nav" onde estarao dispostos o logotipo do site e os links das abas que o site apresneta.

#Description
Desenvolver um Menu Suspenso utilizando a estrutura HTML "nav", onde ficariam dispostos os links de direcionamento para as "abas "ou "sessões do site", o logotipo do site, e a estrutura do buscador. Mesmo o site sendo um SPA o menu suspenso/flutuante NAV ainda encaixa legal pois o link leva o usuario à sessao ou ponto chave no site onde a informaçao biscada esta disposta.

PS: O Elemento HTML de Navegação ("nav") representa uma seção de uma página que aponta para outras páginas ou para outras áreas da página, ou seja, uma seção com links de navegação.

#Screenshots
<img width="583" alt="Captura de tela 2023-11-22 112713" src="https://github.com/netrometro/gc-at2/assets/60446351/efbdef60-8d94-446b-a76e-3ab43ab8a930">

<img width="565" alt="Captura de tela 2023-11-22 113935" src="https://github.com/netrometro/gc-at2/assets/60446351/594f7a21-6dd8-49c6-8521-96ca94032d49">

Sugestão: Usar as referencias apresentadas no site a seguir: https://www.w3schools.com/css/css_navbar.asp

#Task

- [ ] Desenvolver a estrutura do Nav (Conteiner principal e conteiners internos)
- [ ] Mapear os links com as Sessões do site e aloca-los nos conteiners internos
- [ ] Integrar o logotipo do site ao menu suspenso(Converter em uma nova Issues)
- [ ] Integrar o espaço de busca(barra de pesquisa) ao menu suspenso(Converter em uma nova Issues) #5
- [ ] Estilizaçao do Menu Flutuante de acordo com a peleta de cores pré-definida(Converter em uma nova Issues)

**Comment by GabrielFerreiraSilva** [comment]
Sugestão de tarefas para a implementação do menu:

- [ ] Implementação do contêiner principal e dos contêineres internos 

- [ ] Ligação dos elementos do menu com os links de suas respectivas abas

- [ ] Estilizar o menu de acordo com o estilo seguido pelo restante da página

**Comment by Pedro-Bezerra** [comment]
Estou implementando esta issue - Pedro Correia
