### ISSUE TITLE
Cabeçalho da pagina

### ISSUE THREAD

**Issue by mota-pedro** [netrometro/gc-at2#6]
Description
O site precisa de um cabeçalho contendo o nome da universidade 

Tasks

- [ ] Criar um header
- [ ] Inserir nome da universidade

**Comment by JotaTavares** [comment]
Estou implementando essa feature - Júlia

**Comment by MatheusInte** [comment]
Vou comentar essa!

**Comment by MateusVasc** [comment]
Adicionar links para guiar o usuário pelo site ao cabeçalho.

Tasks:

- [ ] Criar um cabeçalho.
- [ ] Inserir nome da universidade.
- [ ] Inserir links guia para navegação do usuário.

**Comment by anna-victoria** [comment]
**Descrição**
Para o cabeçalho, é necessario ter o nome do site, ou sigla (Por exemplo: DPPE, Divulgação de projetos de pesquisa e extensão), e ter a logo da upe

**Tasks**

- [ ] Adicionar titulo do site
- [ ] Adicionar logo

**Comment by mylenamahatma** [comment]
vou implementar essa issue
