### ISSUE TITLE
Criar seção "sobre a UPE"

### ISSUE THREAD

**Issue by jdbsn** [netrometro/gc-at2#9]
#### Description
Adicionar uma seção que fala a respeito da UPE.

#### Files
Utilizar o arquivo index.html.

#### Tasks
- [ ] Criar uma div;
- [ ] Adicionar titulo informações relevantes da UPE dentro da div.

**Comment by allast101** [comment]
EStou implementando essa feature - Alina

**Comment by mylenamahatma** [comment]
**Descrição**
Sugestão de adições na issue. 

**Arquivo**
Criar um arquivo com nome SobreUpe.html

**Atividades**
O que será implementado na página SobreUpe.html

- [ ] é preciso adicionar link para o site da upe. 
- [ ] adicionar contatos de maneira destacada do texto.

**Comment by PedroFerreiraLopes** [comment]
Vou implementar essa!

João Pedro
